// S.A.H.A.S. location data.
// Both the Hindi (indianLocations) and English (indianLocationsEn) maps contain
// the SAME full set of states and equivalent district lists, so that toggling
// the language never drops states or leaves a state without selectable districts.

export const indianLocations: Record<string, string[]> = {
  'अंडमान और निकोबार द्वीप': ['निकोबार', 'उत्तर और मध्य अंडमान', 'दक्षिण अंडमान'],
  'आंध्र प्रदेश': [
    'अनंतपुर',
    'चित्तूर',
    'पूर्व गोदावरी',
    'गुंटूर',
    'कृष्णा',
    'कुर्नूल',
    'नलगोंडा',
    'प्रकाशम',
    'नेल्लोर',
    'कड़प्पा',
    'श्रीकाकुलम',
    'विशाखापत्तनम',
    'विजयनगरम',
    'पश्चिम गोदावरी',
  ],
  'अरुणाचल प्रदेश': [
    'अंजॉ',
    'चांग्लांग',
    'पूर्व कामेंग',
    'पूर्व सियांग',
    'कुरूंग कुमे',
    'लोहित',
    'लोअर दिबांग घाटी',
    'लोअर सुबनसिरी',
    'पापुम पारे',
    'तवांग',
    'तिरप',
    'अपर दिबांग घाटी',
    'अपर सुबनसिरी',
    'पश्चिम कामेंग',
    'पश्चिम सियांग',
  ],
  'असम': [
    'बक्सा',
    'बारपेटा',
    'बोंगाईगांव',
    'चिरांग',
    'दरांग',
    'धेमाजी',
    'धुबरी',
    'डिब्रूगढ़',
    'डिमा हसाओ',
    'दीमापुर',
    'गोलपारा',
    'गोलाघाट',
    'हैलाकांडी',
    'जोरहाट',
    'कामरूप',
    'कामरूप महानगर',
    'कार्बी आंगलोंग',
    'करीमगंज',
    'कोकराझार',
    'लखीमपुर',
    'मोरीगांव',
    'नगांव',
    'नलबारी',
    'सिबसागर',
    'सोनितपुर',
    'तिनसुकिया',
    'उदलगुड़ी',
  ],
  'बिहार': [
    'अररिया',
    'अरवल',
    'औरंगाबाद',
    'बांका',
    'बेगूसराय',
    'भागलपुर',
    'भोजपुर',
    'बक्सर',
    'दरभंगा',
    'पूर्वी चंपारण',
    'गया',
    'गोपालगंज',
    'जमुई',
    'जहानाबाद',
    'कैमूर',
    'कटिहार',
    'खगड़िया',
    'किशनगंज',
    'लखीसराय',
    'मधेपुरा',
    'मधुबनी',
    'मुंगेर',
    'मुजफ्फरपुर',
    'नालंदा',
    'नवादा',
    'पटना',
    'पूर्णिया',
    'रोहतास',
    'सहरसा',
    'समस्तीपुर',
    'सारण',
    'शेखपुरा',
    'शिवहर',
    'सीतामढ़ी',
    'सीवान',
    'सुपौल',
    'वैशाली',
    'पश्चिमी चंपारण',
  ],
  'चंडीगढ़': ['चंडीगढ़'],
  'छत्तीसगढ़': [
    'बलोद',
    'बलौदाबाजार-भाटापारा',
    'बलरामपुर',
    'बस्तर',
    'बेमेतरा',
    'बीजापुर',
    'बिलासपुर',
    'दंतेवाड़ा',
    'धमतरी',
    'दुर्ग',
    'गरियाबंद',
    'गौरेला-पेंड्रा-मरवाही',
    'जांजगीर-चांपा',
    'जशपुर',
    'कबीरधाम',
    'कांकेर',
    'कोंडागांव',
    'कोरबा',
    'कोरिया',
    'महासमुंद',
    'मनेंद्रगढ़-चिरमिरी-भरतपुर',
    'मुंगेली',
    'नारायणपुर',
    'रायगढ़',
    'रायपुर',
    'राजनांदगांव',
    'सुकमा',
    'सूरजपुर',
    'सुरगुजा',
  ],
  'दादरा और नगर हवेली और दमन और दीव': ['दादरा और नगर हवेली', 'दमन', 'दीव'],
  'दिल्ली': ['दिल्ली', 'उत्तर दिल्ली', 'दक्षिण दिल्ली', 'पूर्व दिल्ली', 'पश्चिम दिल्ली'],
  'गोवा': ['उत्तर गोवा', 'दक्षिण गोवा'],
  'गुजरात': [
    'अहमदाबाद',
    'अमरेली',
    'आणंद',
    'आरवली',
    'बनासकांठा',
    'भरूच',
    'भावनगर',
    'बोटाद',
    'छोटा उदयपुर',
    'दाहोद',
    'दांग',
    'देवभूमि द्वारिका',
    'गांधीनगर',
    'गिर सोमनाथ',
    'जामनगर',
    'जूनागढ़',
    'कच्छ',
    'खेड़ा',
    'महीसागर',
    'मेहसाणा',
    'मोरबी',
    'नर्मदा',
    'नवसारी',
    'पंचमहल',
    'पाटन',
    'पोरबंदर',
    'राजकोट',
    'साबरकांठा',
    'सूरत',
    'सुरेंद्रनगर',
    'तापी',
    'वडोदरा',
    'वलसाड',
  ],
  'हरियाणा': [
    'अंबाला',
    'भिवानी',
    'चरखी दादरी',
    'फरीदाबाद',
    'फतेहाबाद',
    'गुरुग्राम',
    'हिसार',
    'झज्जर',
    'जींद',
    'कैथल',
    'करनाल',
    'कुरुक्षेत्र',
    'महेंद्रगढ़',
    'नूंह',
    'पलवल',
    'पंचकूला',
    'पानीपत',
    'रेवाड़ी',
    'रोहतक',
    'सिरसा',
    'सोनीपत',
    'यमुनानगर',
  ],
  'हिमाचल प्रदेश': [
    'बिलासपुर',
    'चंबा',
    'हमीरपुर',
    'कांगड़ा',
    'किन्नौर',
    'कुल्लू',
    'लाहौल और स्पीति',
    'मंडी',
    'शिमला',
    'सिरमौर',
    'सोलन',
    'उना',
  ],
  'जम्मू और कश्मीर': [
    'अनंतनाग',
    'बांदीपोरा',
    'बारामूला',
    'बडगाम',
    'डोडा',
    'गांदरबल',
    'जम्मू',
    'कठुआ',
    'किश्तवाड़',
    'कुलगाम',
    'कुपवाड़ा',
    'पुलवामा',
    'पुंछ',
    'राजौरी',
    'रामबन',
    'रियासी',
    'संबा',
    'श्रीनगर',
    'उधमपुर',
  ],
  'झारखंड': [
    'बोकारो',
    'चतरा',
    'देवघर',
    'धनबाद',
    'दुमका',
    'पूर्वी सिंहभूमि',
    'गढ़वा',
    'गिरिडीह',
    'गोड्डा',
    'गुमला',
    'हजारीबाग',
    'जामताड़ा',
    'खूंटी',
    'कोडरमा',
    'लातेहार',
    'लोहरदग्गा',
    'पलामू',
    'रामगढ़',
    'रांची',
    'साहेबगंज',
    'सरायकेला-खरसावां',
    'सिमडेगा',
    'पश्चिमी सिंहभूमि',
  ],
  'कर्नाटक': [
    'बागलकोट',
    'बेंगलुरु शहरी',
    'बेंगलुरु ग्रामीण',
    'बेलगाम',
    'बल्लारी',
    'बीदर',
    'विजयपुरा',
    'चामराजनगर',
    'चिक्कबल्लापुर',
    'चिक्कमगलुरु',
    'चित्रदुर्ग',
    'दक्षिण कन्नड़',
    'दावणगेरे',
    'धारवाड़',
    'गदग',
    'कलबुर्गी',
    'हसन',
    'हावेरी',
    'कोडगु',
    'कोलार',
    'कोप्पल',
    'मांड्या',
    'मैसूर',
    'रायचूर',
    'रामनगर',
    'शिवमोग्गा',
    'तुमकुरु',
    'उडुपी',
    'उत्तर कन्नड़',
    'विजयनगर',
    'यादगीर',
  ],
  'केरल': [
    'अलप्पुझा',
    'एर्नाकुलम',
    'इडुक्की',
    'कन्नूर',
    'कासरगोड',
    'कोल्लम',
    'कोट्टयम',
    'कोझीकोड',
    'मलप्पुरम',
    'पलक्कड़',
    'पथानमथिट्टा',
    'तिरुवनंतपुरम',
    'त्रिशूर',
    'वायनाड',
  ],
  'लद्दाख': ['करगिल', 'लेह'],
  'लक्षद्वीप': ['लक्षद्वीप'],
  'मध्य प्रदेश': [
    'अगर मालवा',
    'अलीराजपुर',
    'अनूपपुर',
    'अशोकनगर',
    'बालाघाट',
    'बड़वानी',
    'बैतूल',
    'भिंड',
    'भोपाल',
    'बुरहानपुर',
    'छतरपुर',
    'छिंदवाड़ा',
    'दमोह',
    'दतिया',
    'देवास',
    'धार',
    'डिंडोरी',
    'गुना',
    'ग्वालियर',
    'हरदा',
    'होशंगाबाद',
    'इंदौर',
    'जबलपुर',
    'झाबुआ',
    'कटनी',
    'खंडवा',
    'खरगोन',
    'मंडला',
    'मंदसौर',
    'मुरैना',
    'नरसिंहपुर',
    'नीमच',
    'निवाड़ी',
    'पन्ना',
    'रायसेन',
    'राजगढ़',
    'रतलाम',
    'रीवा',
    'सागर',
    'सतना',
    'सीहोर',
    'सिवनी',
    'शहडोल',
    'शाजापुर',
    'श्योपुर',
    'शिवपुरी',
    'सिंगरौली',
    'टीकमगढ़',
    'उज्जैन',
    'उमरिया',
    'विदिशा',
  ],
  'महाराष्ट्र': [
    'अहमदनगर',
    'अकोला',
    'अमरावती',
    'औरंगाबाद',
    'बीड',
    'भंडारा',
    'बुलढाणा',
    'चंद्रपुर',
    'धुले',
    'गडचिरोली',
    'गोंदिया',
    'हिंगोली',
    'जालगांव',
    'जलना',
    'कोल्हापुर',
    'लातूर',
    'मुंबई सिटी',
    'मुंबई उपनगर',
    'नागपुर',
    'नांदेड़',
    'नंदुरबार',
    'नाशिक',
    'उस्मानाबाद',
    'पालघर',
    'परभणी',
    'पुणे',
    'रायगढ़',
    'रत्नागिरी',
    'सांगली',
    'सतारा',
    'सिंधुदुर्ग',
    'सोलापुर',
    'ठाणे',
    'वर्धा',
    'वाशिम',
    'यवतमाल',
  ],
  'मणिपुर': [
    'बिष्णुपुर',
    'चुराचांदपुर',
    'इंफाल पूर्व',
    'इंफाल पश्चिम',
    'जिरीबाम',
    'काकचिंग',
    'कामजोंग',
    'कांगपोकपी',
    'नोने',
    'फेरज़ॉल',
    'सेनापति',
    'तामेंगलोंग',
    'तेनग्नौपाल',
    'थौबल',
    'उखरूल',
  ],
  'मेघालय': [
    'पूर्वी गारो हिल्स',
    'पूर्वी खासी हिल्स',
    'पूर्वी पश्चिम खासी हिल्स',
    'उत्तर गारो हिल्स',
    'रिभोई',
    'दक्षिण गारो हिल्स',
    'दक्षिण पश्चिम गारो हिल्स',
    'दक्षिण पश्चिम खासी हिल्स',
    'पश्चिम गारो हिल्स',
    'पश्चिम खासी हिल्स',
  ],
  'मिजोरम': [
    'आइजोल',
    'चम्फाई',
    'कोलासिब',
    'लुंगलेई',
    'मामित',
    'सैहा',
    'सैतुआल',
    'सेरछिप',
  ],
  'नागालैंड': [
    'दीमापुर',
    'किफाइरे',
    'कोहिमा',
    'लोंगलेंग',
    'मोकोकचुंग',
    'मोन',
    'नीलांग',
    'नोकलाक',
    'पेरेन',
    'फेक',
    'तुएनसांग',
    'वोखा',
    'जुन्हेबोटो',
  ],
  'ओडिशा': [
    'अंगुल',
    'बालासोर',
    'बरगढ़',
    'बौध',
    'भद्रक',
    'बलांगीर',
    'बरहामपुर',
    'कटक',
    'देवगढ़',
    'ढेंकनाल',
    'गजपति',
    'गंजम',
    'जगतसिंहपुर',
    'जाजपुर',
    'झारसुगुड़ा',
    'कालाहांडी',
    'कंधमाल',
    'केंद्रपाड़ा',
    'केंदुझार',
    'खुर्दा',
    'कोरापुट',
    'मलकानगिरी',
    'मयूरभंज',
    'नबरंगपुर',
    'नयागढ़',
    'नुआपाड़ा',
    'पुरी',
    'रायगढ़ा',
    'सम्बलपुर',
    'सोनपुर',
    'सुंदरगढ़',
  ],
  'पुदुचेरी': ['कराईकल', 'माहे', 'पुदुचेरी', 'यानम'],
  'पंजाब': [
    'अमृतसर',
    'बरनाला',
    'बठिंडा',
    'फरीदकोट',
    'फतेहगढ़ साहिब',
    'फाजिल्का',
    'फिरोजपुर',
    'गुरदासपुर',
    'होशियारपुर',
    'जालंधर',
    'कपूरथला',
    'लुधियाना',
    'मानसा',
    'मोगा',
    'मुक्तसर',
    'नवांशहर',
    'पठानकोट',
    'पटियाला',
    'रूपनगर',
    'संगरूर',
    'शहीद भगत सिंह नगर',
    'तरन तारन',
  ],
  'राजस्थान': [
    'अजमेर',
    'अलवर',
    'बांसवाड़ा',
    'बारां',
    'बाड़मेर',
    'भरतपुर',
    'भीलवाड़ा',
    'बीकानेर',
    'बूंदी',
    'चित्तौड़गढ़',
    'चूरू',
    'दौसा',
    'धौलपुर',
    'डूंगरपुर',
    'गंगानगर',
    'हनुमानगढ़',
    'जयपुर',
    'जैसलमेर',
    'जालोर',
    'झालावाड़',
    'झुंझुनू',
    'जोधपुर',
    'करौली',
    'कोटा',
    'नागौर',
    'पाली',
    'प्रतापगढ़',
    'राजसमंद',
    'सवाई माधोपुर',
    'सीकर',
    'सिरोही',
    'टोंक',
    'उदयपुर',
  ],
  'सिक्किम': ['पूर्वी सिक्किम', 'उत्तरी सिक्किम', 'दक्षिण सिक्किम', 'पश्चिमी सिक्किम'],
  'तमिलनाडु': [
    'अरियालुर',
    'चेन्नई',
    'कोयंबटूर',
    'कडलूर',
    'धर्मपुरी',
    'डिंडीगुल',
    'इरोड',
    'कांचीपुरम',
    'कन्याकुमारी',
    'करूर',
    'कृष्णागिरि',
    'मदुरै',
    'नागापट्टिनम',
    'नामक्कल',
    'नीलगिरि',
    'पेरंबलूर',
    'पुदुकोट्टई',
    'रामनाथपुरम',
    'रानीपेट',
    'सलेम',
    'शिवगंगा',
    'तेनकासी',
    'तंजावुर',
    'तेनी',
    'तूतुकुड़ी',
    'तिरुचिरापल्ली',
    'तिरुनेलवेली',
    'तिरुपत्तूर',
    'तिरुपुर',
    'तिरुवल्लूर',
    'तिरुवन्नामलई',
    'तिरुवरूर',
    'वेल्लोर',
    'विल्लुपुरम',
    'विरुधुनगर',
  ],
  'तेलंगाना': [
    'आदिलाबाद',
    'भद्राद्रि कोठागुडेम',
    'हैदराबाद',
    'जगित्याल',
    'जनगांव',
    'जयशंकर भूपालपल्ली',
    'जोगुलांबा गदवाल',
    'कामारेड्डी',
    'करीमनगर',
    'खम्मम',
    'कुमुराम भीम',
    'महबूबनगर',
    'महबूबाबाद',
    'मंचेरियल',
    'मेडक',
    'मेडचल-मलकाजगिरि',
    'मुलुगु',
    'नागरकर्नूल',
    'नलगोंडा',
    'नारायणपेट',
    'निर्मल',
    'निजामाबाद',
    'पेद्दापल्ली',
    'राजन्ना सिरिसिल्ला',
    'रंगारेड्डी',
    'संगारेड्डी',
    'सिद्दीपेट',
    'सूर्यापेट',
    'विकाराबाद',
    'वानापर्थी',
    'वारंगल शहरी',
    'वारंगल ग्रामीण',
    'यदाद्री भुवनगिरि',
  ],
  'त्रिपुरा': [
    'धलाई',
    'गोमती',
    'खोवाई',
    'उत्तर त्रिपुरा',
    'सिपाहीजाला',
    'दक्षिण त्रिपुरा',
    'उनाकोटी',
    'पश्चिम त्रिपुरा',
  ],
  'उत्तर प्रदेश': [
    'आगरा',
    'अलीगढ़',
    'अम्बेडकरनगर',
    'अमेठी',
    'अमरोहा',
    'औरैया',
    'अयोध्या',
    'आज़मगढ़',
    'बागपत',
    'बहराइच',
    'बलिया',
    'बलरामपुर',
    'बांदा',
    'बाराबंकी',
    'बरेली',
    'बस्ती',
    'भदोही',
    'बिजनौर',
    'बदायूं',
    'बुलंदशहर',
    'चंदौली',
    'चित्रकूट',
    'देवरिया',
    'एटा',
    'इटावा',
    'फर्रुखाबाद',
    'फतेहपुर',
    'फिरोजाबाद',
    'गौतम बुद्ध नगर',
    'गाजियाबाद',
    'गाजीपुर',
    'गोंडा',
    'गोरखपुर',
    'हमीरपुर',
    'हापुड़',
    'हरदोई',
    'हाथरस',
    'जालौन',
    'जौनपुर',
    'झांसी',
    'कन्नौज',
    'कानपुर देहात',
    'कानपुर नगर',
    'कासगंज',
    'कौशांबी',
    'कुशीनगर',
    'लखीमपुर खीरी',
    'ललितपुर',
    'लखनऊ',
    'महाराजगंज',
    'महोबा',
    'मैनपुरी',
    'मथुरा',
    'मऊ',
    'मेरठ',
    'मिर्जापुर',
    'मुरादाबाद',
    'मुजफ्फरनगर',
    'पीलीभीत',
    'प्रतापगढ़',
    'प्रयागराज',
    'रायबरेली',
    'रामपुर',
    'सहारनपुर',
    'संभल',
    'संत कबीर नगर',
    'शाहजहांपुर',
    'शामली',
    'श्रावस्ती',
    'सिद्धार्थनगर',
    'सीतापुर',
    'सोनभद्र',
    'सुल्तानपुर',
    'उन्नाव',
    'वाराणसी',
  ],
  'उत्तराखंड': [
    'अल्मोड़ा',
    'बागेश्वर',
    'चमोली',
    'चंपावत',
    'देहरादून',
    'हरिद्वार',
    'नैनीताल',
    'पौड़ी गढ़वाल',
    'पिथौरागढ़',
    'रुद्रप्रयाग',
    'टिहरी गढ़वाल',
    'उधम सिंह नगर',
    'उत्तरकाशी',
  ],
  'पश्चिम बंगाल': [
    'अलीपुरद्वार',
    'बांकुड़ा',
    'बर्द्धमान',
    'बीरभूम',
    'कोलकाता',
    'दक्षिण 24 परगना',
    'दार्जिलिंग',
    'हुगली',
    'हावड़ा',
    'जलपाईगुड़ी',
    'झारग्राम',
    'कालिम्पोंग',
    'मालदा',
    'मुर्शिदाबाद',
    'नदिया',
    'उत्तर 24 परगना',
    'पश्चिम बर्द्धमान',
    'पश्चिम मेदिनीपुर',
    'पूर्व मेदिनीपुर',
    'पुरुलिया',
    'दक्षिण दिनाजपुर',
    'उत्तर दिनाजपुर',
  ],
}

// English state names (mirrors the Hindi map above — same states, same districts)
export const indianLocationsEn: Record<string, string[]> = {
  'Andaman and Nicobar Islands': ['Nicobar', 'North and Middle Andaman', 'South Andaman'],
  'Andhra Pradesh': [
    'Anantapur',
    'Chittoor',
    'East Godavari',
    'Guntur',
    'Krishna',
    'Kurnool',
    'Nalgonda',
    'Prakasam',
    'Nellore',
    'Kadapa',
    'Srikakulam',
    'Visakhapatnam',
    'Vizianagaram',
    'West Godavari',
  ],
  'Arunachal Pradesh': [
    'Anjaw',
    'Changlang',
    'East Kameng',
    'East Siang',
    'Kurung Kumey',
    'Lohit',
    'Lower Dibang Valley',
    'Lower Subansiri',
    'Papum Pare',
    'Tawang',
    'Tirap',
    'Upper Dibang Valley',
    'Upper Subansiri',
    'West Kameng',
    'West Siang',
  ],
  'Assam': [
    'Baksa',
    'Barpeta',
    'Bongaigaon',
    'Chirang',
    'Darrang',
    'Dhemaji',
    'Dhubri',
    'Dibrugarh',
    'Dima Hasao',
    'Goalpara',
    'Golaghat',
    'Hailakandi',
    'Jorhat',
    'Kamrup',
    'Kamrup Metropolitan',
    'Karbi Anglong',
    'Karimganj',
    'Kokrajhar',
    'Lakhimpur',
    'Morigaon',
    'Nagaon',
    'Nalbari',
    'Sivasagar',
    'Sonitpur',
    'Tinsukia',
    'Udalguri',
  ],
  'Bihar': [
    'Araria',
    'Arwal',
    'Aurangabad',
    'Banka',
    'Begusarai',
    'Bhagalpur',
    'Bhojpur',
    'Buxar',
    'Darbhanga',
    'East Champaran',
    'Gaya',
    'Gopalganj',
    'Jamui',
    'Jehanabad',
    'Kaimur',
    'Katihar',
    'Khagaria',
    'Kishanganj',
    'Lakhisarai',
    'Madhepura',
    'Madhubani',
    'Munger',
    'Muzaffarpur',
    'Nalanda',
    'Nawada',
    'Patna',
    'Purnia',
    'Rohtas',
    'Saharsa',
    'Samastipur',
    'Saran',
    'Sheikhpura',
    'Sheohar',
    'Sitamarhi',
    'Siwan',
    'Supaul',
    'Vaishali',
    'West Champaran',
  ],
  'Chandigarh': ['Chandigarh'],
  'Chhattisgarh': [
    'Balod',
    'Balodabazar-Bhatapara',
    'Balrampur',
    'Bastar',
    'Bemetara',
    'Bijapur',
    'Bilaspur',
    'Dantewada',
    'Dhamtari',
    'Durg',
    'Gariyaband',
    'Gaurela-Pendra-Marwahi',
    'Janjgir-Champa',
    'Jashpur',
    'Kabirdham',
    'Kanker',
    'Kondagaon',
    'Korba',
    'Koriya',
    'Mahasamund',
    'Manendragarh-Chirmiri-Bharatpur',
    'Mungeli',
    'Narayanpur',
    'Raigarh',
    'Raipur',
    'Rajnandgaon',
    'Sukma',
    'Surajpur',
    'Surguja',
  ],
  'Dadra and Nagar Haveli and Daman and Diu': ['Dadra and Nagar Haveli', 'Daman', 'Diu'],
  'Delhi': ['Delhi', 'North Delhi', 'South Delhi', 'East Delhi', 'West Delhi'],
  'Goa': ['North Goa', 'South Goa'],
  'Gujarat': [
    'Ahmedabad',
    'Amreli',
    'Anand',
    'Aravalli',
    'Banaskantha',
    'Bharuch',
    'Bhavnagar',
    'Botad',
    'Chhota Udaipur',
    'Dahod',
    'Dang',
    'Devbhoomi Dwarka',
    'Gandhinagar',
    'Gir Somnath',
    'Jamnagar',
    'Junagadh',
    'Kutch',
    'Kheda',
    'Mahisagar',
    'Mehsana',
    'Morbi',
    'Narmada',
    'Navsari',
    'Panchmahal',
    'Patan',
    'Porbandar',
    'Rajkot',
    'Sabarkantha',
    'Surat',
    'Surendranagar',
    'Tapi',
    'Vadodara',
    'Valsad',
  ],
  'Haryana': [
    'Ambala',
    'Bhiwani',
    'Charkhi Dadri',
    'Faridabad',
    'Fatehabad',
    'Gurugram',
    'Hisar',
    'Jhajjar',
    'Jind',
    'Kaithal',
    'Karnal',
    'Kurukshetra',
    'Mahendragarh',
    'Nuh',
    'Palwal',
    'Panchkula',
    'Panipat',
    'Rewari',
    'Rohtak',
    'Sirsa',
    'Sonipat',
    'Yamunanagar',
  ],
  'Himachal Pradesh': [
    'Bilaspur',
    'Chamba',
    'Hamirpur',
    'Kangra',
    'Kinnaur',
    'Kullu',
    'Lahaul and Spiti',
    'Mandi',
    'Shimla',
    'Sirmaur',
    'Solan',
    'Una',
  ],
  'Jammu and Kashmir': [
    'Anantnag',
    'Bandipora',
    'Baramulla',
    'Budgam',
    'Doda',
    'Ganderbal',
    'Jammu',
    'Kathua',
    'Kishtwar',
    'Kulgam',
    'Kupwara',
    'Pulwama',
    'Poonch',
    'Rajouri',
    'Ramban',
    'Reasi',
    'Samba',
    'Srinagar',
    'Udhampur',
  ],
  'Jharkhand': [
    'Bokaro',
    'Chatra',
    'Deoghar',
    'Dhanbad',
    'Dumka',
    'East Singhbhum',
    'Garhwa',
    'Giridih',
    'Godda',
    'Gumla',
    'Hazaribagh',
    'Jamtara',
    'Khunti',
    'Koderma',
    'Latehar',
    'Lohardaga',
    'Palamu',
    'Ramgarh',
    'Ranchi',
    'Sahebganj',
    'Saraikela-Kharsawan',
    'Simdega',
    'West Singhbhum',
  ],
  'Karnataka': [
    'Bagalkot',
    'Bengaluru Urban',
    'Bengaluru Rural',
    'Belagavi',
    'Ballari',
    'Bidar',
    'Vijayapura',
    'Chamarajanagar',
    'Chikkaballapur',
    'Chikkamagaluru',
    'Chitradurga',
    'Dakshina Kannada',
    'Davanagere',
    'Dharwad',
    'Gadag',
    'Kalaburagi',
    'Hassan',
    'Haveri',
    'Kodagu',
    'Kolar',
    'Koppal',
    'Mandya',
    'Mysuru',
    'Raichur',
    'Ramanagara',
    'Shivamogga',
    'Tumakuru',
    'Udupi',
    'Uttara Kannada',
    'Vijayanagara',
    'Yadgir',
  ],
  'Kerala': [
    'Alappuzha',
    'Ernakulam',
    'Idukki',
    'Kannur',
    'Kasaragod',
    'Kollam',
    'Kottayam',
    'Kozhikode',
    'Malappuram',
    'Palakkad',
    'Pathanamthitta',
    'Thiruvananthapuram',
    'Thrissur',
    'Wayanad',
  ],
  'Ladakh': ['Kargil', 'Leh'],
  'Lakshadweep': ['Lakshadweep'],
  'Madhya Pradesh': [
    'Agar Malwa',
    'Alirajpur',
    'Anuppur',
    'Ashoknagar',
    'Balaghat',
    'Barwani',
    'Betul',
    'Bhind',
    'Bhopal',
    'Burhanpur',
    'Chhatarpur',
    'Chhindwara',
    'Damoh',
    'Datia',
    'Dewas',
    'Dhar',
    'Dindori',
    'Guna',
    'Gwalior',
    'Harda',
    'Hoshangabad',
    'Indore',
    'Jabalpur',
    'Jhabua',
    'Katni',
    'Khandwa',
    'Khargone',
    'Mandla',
    'Mandsaur',
    'Morena',
    'Narsinghpur',
    'Neemuch',
    'Niwari',
    'Panna',
    'Raisen',
    'Rajgarh',
    'Ratlam',
    'Rewa',
    'Sagar',
    'Satna',
    'Sehore',
    'Seoni',
    'Shahdol',
    'Shajapur',
    'Sheopur',
    'Shivpuri',
    'Singrauli',
    'Tikamgarh',
    'Ujjain',
    'Umaria',
    'Vidisha',
  ],
  'Maharashtra': [
    'Ahmednagar',
    'Akola',
    'Amravati',
    'Aurangabad',
    'Beed',
    'Bhandara',
    'Buldhana',
    'Chandrapur',
    'Dhule',
    'Gadchiroli',
    'Gondia',
    'Hingoli',
    'Jalgaon',
    'Jalna',
    'Kolhapur',
    'Latur',
    'Mumbai City',
    'Mumbai Suburban',
    'Nagpur',
    'Nanded',
    'Nandurbar',
    'Nashik',
    'Osmanabad',
    'Palghar',
    'Parbhani',
    'Pune',
    'Raigad',
    'Ratnagiri',
    'Sangli',
    'Satara',
    'Sindhudurg',
    'Solapur',
    'Thane',
    'Wardha',
    'Washim',
    'Yavatmal',
  ],
  'Manipur': [
    'Bishnupur',
    'Churachandpur',
    'Imphal East',
    'Imphal West',
    'Jiribam',
    'Kakching',
    'Kamjong',
    'Kangpokpi',
    'Noney',
    'Pherzawl',
    'Senapati',
    'Tamenglong',
    'Tengnoupal',
    'Thoubal',
    'Ukhrul',
  ],
  'Meghalaya': [
    'East Garo Hills',
    'East Khasi Hills',
    'Eastern West Khasi Hills',
    'North Garo Hills',
    'Ri-Bhoi',
    'South Garo Hills',
    'South West Garo Hills',
    'South West Khasi Hills',
    'West Garo Hills',
    'West Khasi Hills',
  ],
  'Mizoram': ['Aizawl', 'Champhai', 'Kolasib', 'Lawngtlai', 'Lunglei', 'Mamit', 'Saiha', 'Saitual', 'Serchhip'],
  'Nagaland': [
    'Dimapur',
    'Kiphire',
    'Kohima',
    'Longleng',
    'Mokokchung',
    'Mon',
    'Noklak',
    'Nokalak',
    'Peren',
    'Phek',
    'Tuensang',
    'Wokha',
    'Zunheboto',
  ],
  'Odisha': [
    'Angul',
    'Balasore',
    'Bargarh',
    'Boudh',
    'Bhadrak',
    'Balangir',
    'Berhampur',
    'Cuttack',
    'Deogarh',
    'Dhenkanal',
    'Gajapati',
    'Ganjam',
    'Jagatsinghpur',
    'Jajpur',
    'Jharsuguda',
    'Kalahandi',
    'Kandhamal',
    'Kendrapara',
    'Kendujhar',
    'Khordha',
    'Koraput',
    'Malkangiri',
    'Mayurbhanj',
    'Nabarangpur',
    'Nayagarh',
    'Nuapada',
    'Puri',
    'Rayagada',
    'Sambalpur',
    'Sonepur',
    'Sundargarh',
  ],
  'Puducherry': ['Karaikal', 'Mahe', 'Puducherry', 'Yanam'],
  'Punjab': [
    'Amritsar',
    'Barnala',
    'Bathinda',
    'Faridkot',
    'Fatehgarh Sahib',
    'Fazilka',
    'Firozpur',
    'Gurdaspur',
    'Hoshiarpur',
    'Jalandhar',
    'Kapurthala',
    'Ludhiana',
    'Mansa',
    'Moga',
    'Muktsar',
    'Nawanshahr',
    'Pathankot',
    'Patiala',
    'Rupnagar',
    'Sangrur',
    'Shaheed Bhagat Singh Nagar',
    'Tarn Taran',
  ],
  'Rajasthan': [
    'Ajmer',
    'Alwar',
    'Banswara',
    'Baran',
    'Barmer',
    'Bharatpur',
    'Bhilwara',
    'Bikaner',
    'Bundi',
    'Chittorgarh',
    'Churu',
    'Dausa',
    'Dholpur',
    'Dungarpur',
    'Ganganagar',
    'Hanumangarh',
    'Jaipur',
    'Jaisalmer',
    'Jalore',
    'Jhalawar',
    'Jhunjhunu',
    'Jodhpur',
    'Karauli',
    'Kota',
    'Nagaur',
    'Pali',
    'Pratapgarh',
    'Rajsamand',
    'Sawai Madhopur',
    'Sikar',
    'Sirohi',
    'Tonk',
    'Udaipur',
  ],
  'Sikkim': ['East Sikkim', 'North Sikkim', 'South Sikkim', 'West Sikkim'],
  'Tamil Nadu': [
    'Ariyalur',
    'Chennai',
    'Coimbatore',
    'Cuddalore',
    'Dharmapuri',
    'Dindigul',
    'Erode',
    'Kancheepuram',
    'Kanyakumari',
    'Karur',
    'Krishnagiri',
    'Madurai',
    'Nagapattinam',
    'Namakkal',
    'Nilgiris',
    'Perambalur',
    'Pudukkottai',
    'Ramanathapuram',
    'Ranipet',
    'Salem',
    'Sivaganga',
    'Tenkasi',
    'Thanjavur',
    'Theni',
    'Thoothukudi',
    'Tiruchirappalli',
    'Tirunelveli',
    'Tirupattur',
    'Tiruppur',
    'Tiruvallur',
    'Tiruvannamalai',
    'Tiruvarur',
    'Vellore',
    'Villupuram',
    'Virudhunagar',
  ],
  'Telangana': [
    'Adilabad',
    'Bhadradri Kothagudem',
    'Hyderabad',
    'Jagtial',
    'Jangaon',
    'Jayashankar Bhupalpally',
    'Jogulamba Gadwal',
    'Kamareddy',
    'Karimnagar',
    'Khammam',
    'Komaram Bheem',
    'Mahabubnagar',
    'Mahabubabad',
    'Mancherial',
    'Medak',
    'Medchal-Malkajgiri',
    'Mulugu',
    'Nagarkurnool',
    'Nalgonda',
    'Narayanpet',
    'Nirmal',
    'Nizamabad',
    'Peddapalli',
    'Rajanna Sircilla',
    'Rangareddy',
    'Sangareddy',
    'Siddipet',
    'Suryapet',
    'Vikarabad',
    'Wanaparthy',
    'Warangal Urban',
    'Warangal Rural',
    'Yadadri Bhuvanagiri',
  ],
  'Tripura': [
    'Dhalai',
    'Gomati',
    'Khowai',
    'North Tripura',
    'Sipahijala',
    'South Tripura',
    'Unakoti',
    'West Tripura',
  ],
  'Uttar Pradesh': [
    'Agra',
    'Aligarh',
    'Ambedkar Nagar',
    'Amethi',
    'Amroha',
    'Auraiya',
    'Ayodhya',
    'Azamgarh',
    'Baghpat',
    'Bahraich',
    'Ballia',
    'Balrampur',
    'Banda',
    'Barabanki',
    'Bareilly',
    'Basti',
    'Bhadohi',
    'Bijnor',
    'Budaun',
    'Bulandshahr',
    'Chandauli',
    'Chitrakoot',
    'Deoria',
    'Etah',
    'Etawah',
    'Farrukhabad',
    'Fatehpur',
    'Firozabad',
    'Gautam Buddha Nagar',
    'Ghaziabad',
    'Ghazipur',
    'Gonda',
    'Gorakhpur',
    'Hamirpur',
    'Hapur',
    'Hardoi',
    'Hathras',
    'Jalaun',
    'Jaunpur',
    'Jhansi',
    'Kannauj',
    'Kanpur Dehat',
    'Kanpur Nagar',
    'Kasganj',
    'Kaushambi',
    'Kushinagar',
    'Lakhimpur Kheri',
    'Lalitpur',
    'Lucknow',
    'Maharajganj',
    'Mahoba',
    'Mainpuri',
    'Mathura',
    'Mau',
    'Meerut',
    'Mirzapur',
    'Moradabad',
    'Muzaffarnagar',
    'Pilibhit',
    'Pratapgarh',
    'Prayagraj',
    'Raebareli',
    'Rampur',
    'Saharanpur',
    'Sambhal',
    'Sant Kabir Nagar',
    'Shahjahanpur',
    'Shamli',
    'Shravasti',
    'Siddharthnagar',
    'Sitapur',
    'Sonbhadra',
    'Sultanpur',
    'Unnao',
    'Varanasi',
  ],
  'Uttarakhand': [
    'Almora',
    'Bageshwar',
    'Chamoli',
    'Champawat',
    'Dehradun',
    'Haridwar',
    'Nainital',
    'Pauri Garhwal',
    'Pithoragarh',
    'Rudraprayag',
    'Tehri Garhwal',
    'Udham Singh Nagar',
    'Uttarkashi',
  ],
  'West Bengal': [
    'Alipurduar',
    'Bankura',
    'Bardhaman',
    'Birbhum',
    'Kolkata',
    'South 24 Parganas',
    'Darjeeling',
    'Hooghly',
    'Howrah',
    'Jalpaiguri',
    'Jhargram',
    'Kalimpong',
    'Malda',
    'Murshidabad',
    'Nadia',
    'North 24 Parganas',
    'Paschim Bardhaman',
    'Paschim Medinipur',
    'Purba Medinipur',
    'Purulia',
    'Dakshin Dinajpur',
    'Uttar Dinajpur',
  ],
}

// Helper function to get cities for a district (can be expanded later)
export function getCitiesForDistrict(_state: string, _district: string): string[] {
  // For now, return empty array - this can be expanded with actual city data
  return []
}
