import type { Language } from './types'

export const strings = {
  hi: {
    reporting: {
      title: 'घुसपैठिया रिपोर्ट करें',
      subtitle: 'S.A.H.A.S. सदस्य के रूप में अपने क्षेत्र में किसी भी संदिग्ध गतिविधि की रिपोर्ट करें।',
      registerTitle: 'पहले सदस्य बनें',
      registerSubtitle: 'S.A.H.A.S. में पंजीकृत होकर रिपोर्ट करने की शक्ति प्राप्त करें।',
      tabs: {
        newMember: 'नया सदस्य',
        returningMember: 'पहले से सदस्य',
      },
      registration: {
        heading: 'S.A.H.A.S. में पंजीकरण करें',
        firstName: 'पहला नाम',
        lastName: 'अंतिम नाम',
        phoneNumber: 'फोन नंबर',
        state: 'राज्य',
        district: 'जिला',
        city: 'शहर',
        selectState: 'राज्य चुनें',
        selectDistrict: 'जिला चुनें',
        selectCity: 'शहर चुनें',
        sendOtp: 'OTP भेजें',
        enterOtp: 'OTP दर्ज करें',
        verifyOtp: 'OTP सत्यापित करें',
        resendOtp: 'OTP फिर से भेजें',
        submitButton: 'सदस्य बनें',
      },
      quickAuth: {
        heading: 'पुनः प्रमाणीकरण करें',
        phoneNumber: 'आपका फोन नंबर',
        sendOtp: 'OTP भेजें',
        enterOtp: 'OTP दर्ज करें',
        verifyOtp: 'सत्यापित करें',
        resendOtp: 'OTP फिर से भेजें',
      },
      reportForm: {
        heading: 'घटना की रिपोर्ट करें',
        memberInfo: 'आपकी जानकारी',
        incidentDetails: 'घटना की विवरण',
        basis: 'आधार',
        basisOptions: {
          suspicious: 'संदिग्ध व्यवहार',
          disturbance: 'व्यवधान',
          vandalism: 'तोड़फोड़',
          other: 'अन्य',
        },
        location: 'स्थान',
        date: 'तारीख',
        time: 'समय',
        description: 'विवरण',
        photos: 'फोटो (अधिकतम 2)',
        addPhoto: 'फोटो जोड़ें',
        pickLocation: 'मानचित्र से स्थान चुनें',
        submitReport: 'रिपोर्ट जमा करें',
        review: 'समीक्षा',
      },
      success: {
        memberCreated: 'आप सफलतापूर्वक S.A.H.A.S. के सदस्य बन गए हैं।',
        memberId: 'आपकी सदस्य ID',
        reportSubmitted: 'आपकी रिपोर्ट सफलतापूर्वक जमा की गई है।',
        reportId: 'रिपोर्ट ID',
        shareMessage: 'अपनी सदस्य ID सुरक्षित रखें। भविष्य में रिपोर्ट करने के लिए इसकी आवश्यकता होगी।',
      },
      errors: {
        invalidPhone: 'कृपया एक वैध फोन नंबर दर्ज करें।',
        invalidOtp: 'कृपया एक वैध OTP दर्ज करें।',
        required: 'यह फील्ड आवश्यक है।',
        selectState: 'कृपया एक राज्य चुनें।',
        selectDistrict: 'कृपया एक जिला चुनें।',
        selectCity: 'कृपया एक शहर चुनें।',
        selectIncident: 'कृपया घटना का प्रकार चुनें।',
        maxPhotos: 'आप केवल 2 फोटो जोड़ सकते हैं।',
      },
      buttons: {
        cancel: 'रद्द करें',
        next: 'अगला',
        back: 'वापस',
        submit: 'जमा करें',
        edit: 'संपादित करें',
        home: 'मुख्य पृष्ठ',
      },
    },
  },
  en: {
    reporting: {
      title: 'Report Intruder Activity',
      subtitle: 'As an S.A.H.A.S. member, report any suspicious activity in your area.',
      registerTitle: 'Become a Member First',
      registerSubtitle: 'Register with S.A.H.A.S. to gain the power to report.',
      tabs: {
        newMember: 'New Member',
        returningMember: 'Returning Member',
      },
      registration: {
        heading: 'Register with S.A.H.A.S.',
        firstName: 'First Name',
        lastName: 'Last Name',
        phoneNumber: 'Phone Number',
        state: 'State',
        district: 'District',
        city: 'City',
        selectState: 'Select State',
        selectDistrict: 'Select District',
        selectCity: 'Select City',
        sendOtp: 'Send OTP',
        enterOtp: 'Enter OTP',
        verifyOtp: 'Verify OTP',
        resendOtp: 'Resend OTP',
        submitButton: 'Become a Member',
      },
      quickAuth: {
        heading: 'Re-authenticate',
        phoneNumber: 'Your Phone Number',
        sendOtp: 'Send OTP',
        enterOtp: 'Enter OTP',
        verifyOtp: 'Verify',
        resendOtp: 'Resend OTP',
      },
      reportForm: {
        heading: 'Report an Incident',
        memberInfo: 'Your Information',
        incidentDetails: 'Incident Details',
        basis: 'Basis',
        basisOptions: {
          suspicious: 'Suspicious Behavior',
          disturbance: 'Disturbance',
          vandalism: 'Vandalism',
          other: 'Other',
        },
        location: 'Location',
        date: 'Date',
        time: 'Time',
        description: 'Description',
        photos: 'Photos (Max 2)',
        addPhoto: 'Add Photo',
        pickLocation: 'Pick Location from Map',
        submitReport: 'Submit Report',
        review: 'Review',
      },
      success: {
        memberCreated: 'You have successfully become an S.A.H.A.S. member.',
        memberId: 'Your Member ID',
        reportSubmitted: 'Your report has been successfully submitted.',
        reportId: 'Report ID',
        shareMessage: 'Keep your Member ID safe. You will need it to report in the future.',
      },
      errors: {
        invalidPhone: 'Please enter a valid phone number.',
        invalidOtp: 'Please enter a valid OTP.',
        required: 'This field is required.',
        selectState: 'Please select a state.',
        selectDistrict: 'Please select a district.',
        selectCity: 'Please select a city.',
        selectIncident: 'Please select an incident type.',
        maxPhotos: 'You can only add up to 2 photos.',
      },
      buttons: {
        cancel: 'Cancel',
        next: 'Next',
        back: 'Back',
        submit: 'Submit',
        edit: 'Edit',
        home: 'Home',
      },
    },
  },
}

export function getString(language: Language, path: string): string {
  const parts = path.split('.')
  let current: any = strings[language]
  for (const part of parts) {
    current = current?.[part]
  }
  return current || path
}
